### PR TITLE
automations/translations

### PR DESCRIPTION
**Pull request by JarbasAl**
for https://gitlocalize.com/users/OpenVoiceOS

### CODE REVIEW

**Comment by mikejgray** [comment]
I thought we agreed this one didn't make sense to translate?

**Comment by JarbasAl** [comment]
depends on intent, and OVOS supports partial translations too  (only some intents translated)

**Comment by mikejgray** [comment]
> depends on intent, and OVOS supports partial translations too (only some intents translated)

Does this automation support partial translation?

**Comment by JarbasAl** [comment]
all intents will show in the UI, we can remove unwanted ones from the translations folder json files (english)

for receiving PRs it can also be partial, ie, the UI doesnt require full tx before we can send PR

**Pull request merged**
