### PR TITLE
feat: malibu stacey and bill and ted easter eggs

### PR DESCRIPTION
**Pull request by mikejgray**
Addresses #28

With thanks to @KathyReid :)

### CODE REVIEW

**Comment by ChanceNCounter** [comment]
Visually LGTM, have not tested.

@KathyReid, could you please clarify which license you meant for the original to bear? It still seems to be carrying the "delete 2/3 of this" template of yore. I assume MIT or Apache, because this dates from after the "feh copylefted Python" eureka, but we need to specify which, so that...

@mikejgray ^ that done, please amend `LICENSE` to reflect that the skill is released under the Apache license 2.0, but portions derive from, list the parents and their licenses, credit the authors (Kathy in this case.) Then a break, then the full text of the license as it currently looks

**Comment by mikejgray** [comment]
@KathyReid Bump - I'd love to incorporate your Malibu Stacey work into this skill, but as Chance said, we want to make sure we get the correct licensing information.

**Comment by mikejgray** [comment]
Hi @KathyReid, I'm sure you're busy. When you get a chance would you please share the original intent for the Malibu Stacey skill license? Thank you!

**Comment by KathyReid** [comment]
Hey @mikejgray, firstly apologies for the radio silence, deep in PhD land. I'm totally open to whatever licence works best for OpenVoiceOS, however the bigger issue I see here is the licensing of the Malibu Stacey content itself - I took it from the internet somewhere, but I don't think it is open licensed. Can we claim fair use here? Not sure? And also not sure if that applies to jurisdictions outside of the United States. 

Best, Kathy

**Comment by mikejgray** [comment]
@KathyReid No worries whatsoever! Thank you for responding. We'll stick with the Apache 2.0 license on the rest of the skill then. As for fair use...I'm not a lawyer, but I definitely see your point. I replaced the licensed sounds with some TTS-generated sounds instead (Nabu Casa cloud TTS, American English, Sara Neural). That should be less of an issue, I would imagine.

**Review by builderjer — APPROVED** [review]

**Pull request merged**
